<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">

	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net8.0-windows</TargetFramework>
		<UseWPF>true</UseWPF>
		<RootNamespace>Orion</RootNamespace>
	</PropertyGroup>

	<ItemGroup>
	  <None Remove="Assets\splash_screen_landscape_450x300.png" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\Orchestrator\Orion.Orchestrator.csproj" />
	  <ProjectReference Include="..\Orion.Core\Orion.Core.csproj" />
	</ItemGroup>

	<ItemGroup>
	  <Resource Include="Assets\splash_screen_landscape_450x300.png" />
	</ItemGroup>

</Project>
